export enum CsvColumnIdentifier {
	ncm_number = 'NUMERO DE ORDEM',
	ncm_name = 'ANOMES',
	ncm_node = 'COD.NCM',
	ncm_description = 'DESCRICAO DO CODIGO NCM',
	country = 'PAIS',
	origin_country = 'PAIS DE ORIGEM',
	aquisition_country = 'PAIS DE AQUISICAO',
	statistical_unit = 'UND.ESTAT',
	measurement_unit = 'UNIDADE DE MEDIDA',
	commercial_measurement = 'UNIDADE COMERC.',
	product_description = 'DESCRICAO DO PRODUTO',
	statistical_quantity = 'QTDE ESTATISTICA',
	net_weight = 'PESO LIQUIDO',
	vmle_dolar = 'VMLE DOLAR',
	vl_freight = 'VL FRETE DOLAR',
	vl_secure = 'VL SEGURO DOLAR',
	commercial_quantity = 'QTD COMERCIAL',
	product_unit_value = 'VALOR UN.PROD.DOLAR',
	total_product_unit = 'TOT.UN.PROD.DOLAR',
	landing_unit = 'UNIDADE DESEMBARQUE',
	resourcefulness_unit = 'UNIDADE DESEMBARACO',
	incoterm = 'INCOTERM',
	nat_information = 'NAT.INFORMACAO',
	dispatch_situation = 'SITUACAO DO DESPACHO',
}